name: Release Notes

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ release/* ]
  pull_request:
    branches: [ main, release/* ]

jobs:
  generate-release-notes:
    name: Generate Release Notes
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for Calculate Version step (e.g. GitVersion)
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }} # So we can commit to protected branches.

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@b82e662a7199df56ac962118e506d9efb9830f82 #v4.1.0
        with:
          versionSpec: '6.4.0'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@b82e662a7199df56ac962118e506d9efb9830f82 #v4.1.0

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@b82e662a7199df56ac962118e506d9efb9830f82 #v4.1.0
        with:
          versionSpec: '0.20.0'

      # If there are no closed issues generating the Github Release will fail because it raises an exception.
      # Work around this by checking for success or no closed issue errors.
      - name: Create Release ${{ steps.gitversion.outputs.majorMinorPatch }}
        run: |
          dotnet gitreleasemanager create --owner ${{ github.repository_owner }} --repository ${{ github.event.repository.name }} --token ${{ secrets.GITHUB_TOKEN }} --milestone v${{ steps.gitversion.outputs.majorMinorPatch }} --logFilePath output.txt || true
          cat output.txt | grep 'No closed issues have been found for milestone\|Drafted release is available at'

      - name: 'Generate Change Log'
        run: |
          dotnet-gitreleasemanager export --token ${{ secrets.GITHUB_TOKEN }} -o '${{ github.repository_owner }}' -r '${{ github.event.repository.name }}' -f 'CHANGELOG.md'
          git add --renormalize CHANGELOG.md
          cat CHANGELOG.md

      - name: 'Commit Change Log if it Changed'
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 #v6.0.1
        with:
          commit_message: Committing auto generated change log.
          file_pattern: CHANGELOG.md